name: Daily Commit

on:
  schedule:
    # Runs at 9:00 AM UTC every day
    - cron: "0 9 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --local user.email "24ds1000046@ds.study.iitm.ac.in"
          git config --local user.name "DevSync Automation Bot"

      - name: Create a commit
        run: |
          # Add a new file or update an existing file (for example, status.txt)
          echo "Commit made on $(date)" >> status.txt
          git add status.txt
          git commit -m "Daily commit for automated update"
          
      - name: Push changes
        run: |
          git push
